before_script:
    - sudo apt-get install libgmp3-dev
    - curl -L http://cpanmin.us | sudo perl - --self-upgrade
    - mkdir ~/perl5
    - perl -Mlocal::lib >> /tmp/local_lib_junk.sh && source /tmp/local_lib_junk.sh
    - sudo chown -R $CI_USER ~/.cpanm ~/perl5
script: "cpanm --installdeps .; perl Build.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
