language: "perl"
perl:
  - "5.14"
  - "5.12"
  - "5.10"
before_script:
    - sudo apt-get install libgmp3-dev
    - cpanm Test::Pod # optional dependency
script: "perl Build.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
